### ISSUE TITLE
upgrade The script

### ISSUE THREAD

**Issue by alsgaozud** [ShafiqSadat/HamsterKeyGen#11]
Develop the script so that Error does not work after choosing a large number of codes, for example 200. The script code turns off

Also, if you could convert this to turn it into a Telegram bot, it would be even better

**Comment by ShafiqSadat** [comment]
rate limit is from game servers not script!

**Comment by alsgaozud** [comment]
oh thanks

You did not answer the second question. Can you put codes for this script so that it can be a Telegram bot?

**Comment by ShafiqSadat** [comment]
You have to do it yourself 

https://t.me/HamsterPromoCodes

this channel uses my script!
