### ISSUE TITLE
pls help me 

### ISSUE THREAD

**Issue by sfpghjgf** [ShafiqSadat/HamsterKeyGen#12]
C:\Users\1\PycharmProjects\HamsterKeyGen\venv\Scripts\python.exe C:\Users\1\PycharmProjects\HamsterKeyGen\main.py 
Select a game:
1: Riding Extreme 3D
2: Chain Cube 2048
3: My Clone Army
4: Train Miner
Enter the game number: 1
Enter the number of keys to generate: 1
Enter the proxy file path (leave empty to use 'proxy.txt'):  What should I enter here?

Please help me . I'm a noob

**Comment by ShafiqSadat** [comment]
Just press enter

**Comment by sfpghjgf** [comment]
C:\Users\1\PycharmProjects\HamsterKeyGen\venv\Scripts\python.exe C:\Users\1\PycharmProjects\HamsterKeyGen\main.py 
Select a game:
1: Riding Extreme 3D
2: Chain Cube 2048
3: My Clone Army
4: Train Miner
Enter the game number: 1
Enter the number of keys to generate: 1
Enter the proxy file path (leave empty to use 'proxy.txt'): 
2024-08-07 11:31:49 | INFO     | 51 - Proxy file proxy.txt not found. No proxies will be used.
2024-08-07 11:31:49 | INFO     | 138 - Generating 1 key(s) for Riding Extreme 3D using proxies from no proxies

**Comment by sfpghjgf** [comment]
Wtf is proxy, Where should I put it?

**Comment by ShafiqSadat** [comment]
If you don't have proxy just press enter and wait for key(s)

**Comment by sfpghjgf** [comment]
Real?

**Comment by sfpghjgf** [comment]
Thank you)
