### ISSUE TITLE
C:\Users\1\PycharmProjects\HamsterKeyGen\venv\Scripts\python.exe C:\Users\1\PycharmProjects\HamsterKeyGen\main.py

### ISSUE THREAD

**Issue by sfpghjgf** [ShafiqSadat/HamsterKeyGen#13]
C:\Users\1\PycharmProjects\HamsterKeyGen\venv\Scripts\python.exe C:\Users\1\PycharmProjects\HamsterKeyGen\main.py 
Select a game:
1: Riding Extreme 3D
2: Chain Cube 2048
3: My Clone Army
4: Train Miner
Enter the game number: 1
Enter the number of keys to generate: 1
Enter the proxy file path (leave empty to use 'proxy.txt'): 
2024-08-07 11:31:49 | INFO     | 51 - Proxy file proxy.txt not found. No proxies will be used.
2024-08-07 11:31:49 | INFO     | 138 - Generating 1 key(s) for Riding Extreme 3D using proxies from no proxies

_Originally posted by @sfpghjgf in https://github.com/ShafiqSadat/HamsterKeyGen/issues/12#issuecomment-2272921999_

**Comment by ShafiqSadat** [comment]
#12 duplicate
