### ISSUE TITLE
From where to get proxies?

### ISSUE THREAD

**Issue by SarcasticBalak** [ShafiqSadat/HamsterKeyGen#15]
Hi there, I want to generate multiple number of keys with only 1 IP address. Its okay if you add slowdown mode which is the most convineient but script must be able to generate keys.

PleASE HELP

**Comment by ShafiqSadat** [comment]
Search on google for buy proxy server!

**Comment by SarcasticBalak** [comment]
Okay, so can't i generate keys with only one IP?

**Comment by ShafiqSadat** [comment]
You can but only 2 to 4 keys each time!

**Comment by SarcasticBalak** [comment]
What's about that slowmode enhancement? What will it bring?

**Comment by ShafiqSadat** [comment]
#8 I will update script ASAP!
