### ISSUE TITLE
Are these codes unique for every device?

### ISSUE THREAD

**Issue by Master811129** [ShafiqSadat/HamsterKeyGen#29]
https://github.com/ShafiqSadat/HamsterKeyGen/blob/4771b0888d4e4ec0f966ca991fcf468d11a44fd0/main.py#L19C1-L41C1

Well, I hope these codes are just be the same on every device. otherwise they can track us back to a "bad " ID and possibly ban us.

**Comment by ShafiqSadat** [comment]
No, Key is not unique for every device!
