### ISSUE TITLE
is there ANY method the developers could find out the codes are generated?

### ISSUE THREAD

**Issue by ololoololoolool** [ShafiqSadat/HamsterKeyGen#41]
is there ANY method the developers could find out the codes are generated?
or they are just Bluffing =)

**Comment by ShafiqSadat** [comment]
Added!

**Comment by ololoololoolool** [comment]
> Added!

added what bro -_-

**Comment by ShafiqSadat** [comment]
Sorry for the incorrect response. I don't believe they can detect it. If they could, their bot wouldn't accept the keys generated by our script!
