### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by vbukhonov** [ShafiqSadat/HamsterKeyGen#46]
Hi! I am 100% sure it is sort of a typo, but there is an error in the numbering of dict's keys.
![Снимок экрана 2024-09-18 в 15 01 56](https://github.com/user-attachments/assets/67bbf915-bf9c-404b-ab29-78943ac2258a)

I can't push branches, so, @ShafiqSadat , could you please fix that?

**Comment by ShafiqSadat** [comment]
Fixed!
