### ISSUE TITLE
Game 4 failed (other games working fine)

### ISSUE THREAD

**Issue by PrincePrikin** [ShafiqSadat/HamsterKeyGen#5]
Failed to login: Unknown error
![image](https://github.com/user-attachments/assets/5d754c26-0567-4150-a98f-96c7eeaba77c)

**Comment by madkite2** [comment]
Please specify saving the generated codes in a text document.

**Comment by ShafiqSadat** [comment]
@PrincePrikin Some games gives error when generate too many keys, for now only generate 1 key each time!

**Comment by madkite2** [comment]
> @PrincePrikin Some games gives error when generate too many keys, for now only generate 1 key each time!

Please add the ability to save generated codes in a text document.

**Comment by ShafiqSadat** [comment]
@madkite2 added!

**Comment by madkite2** [comment]
> @madkite2 added!

oh, thank you
